print( "Chocolate Chip Cookies" )
print( "1 cup butter, softened" )
print( "1 cup white sugar" )
print( "1 cup packed brown sugar" )
print( "2 eggs" )
print( "2 teaspoons vanilla extract" )
print( "3 cups all-purpose flour" )
print( "1 teaspoon baking soda" )
print( "2 teaspoons hot water" )
print( "0.5 teaspoons salt" )
print( "2 cups semisweet chocolate chips" )
print( "1 cup chopped walnuts" )
